version: "3.8"

services:
  backend:
    build:
      context: ./sistema_riego_backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "5006:5006"
    environment:
      - NODE_ENV=production
      - PORT=5006
    depends_on:
      - frontend

  frontend:
    build:
      context: ./sistema_riego
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
